//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClevConWebUI.Models
{
    using Infrastructure;
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Visitor
    {
        public int VisitorId { get; set; }

        [Required]
        [Display(Name = "Name of Visitor")]
        public string Name { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH\\:mm}", ApplyFormatInEditMode =true)]
        public DateTime? Arrived { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH\\:mm}", ApplyFormatInEditMode = true)]
        public DateTime? Departed { get; set; }

        [DataType(DataType.MultilineText)]
        public string Notes { get; set; }

        [Display(Name = "Name of Host")]
        public int HostId { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}", ApplyFormatInEditMode =true)]
        [FutureDate(ErrorMessage="Sorry, you can't register visitors for past dates.")]
        public DateTime? Expected { get; set; }
    
        public virtual Host Host { get; set; }
    }
}
